[package]
name = "roguelike"
version = "0.1.0"
authors = ["Richard Howard <richard@promptworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.15"
specs = { version = "0.15.1", features = ["specs-derive"] }
rand = "0.7.3"

[dependencies.shred]
version = "0.9.4"
features = ["nightly"]
